### ISSUE TITLE
Build Failed: undefined reference to `ss_initiator_task_function'`

### ISSUE THREAD

**Issue by Alex-Beh** [TIERS/dwm1001_localization_and_calibration#1]
Hello, when I trying to compile the code, it report the following error:
`ss_twr_resp/main.c:187: undefined reference to ss_initiator_task_function`.

Then I copy the function definition in dwm1001-example and paste into ss_init_main.c . May I know do you encounter this error also? Do I do it correctly?

And also the Segger Embedded Studio (SES) version V3.34a has been removed in the official download page. So I am using v4.50 to build the file.

**Comment by jopequ** [comment]
Hi, did you replace both `ss_init_main.c` and `main.c`?
We only tried with SES v.3.34, will try newer versions in the future.
